run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - misspell
    - lll
    - goimports
    - nakedret
    - prealloc
    - dogsled
    - bodyclose

linters-settings:
  lll:
    line-length: 120
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G104

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - lll
